version: "3"


services:
# ── HDFS ────────────────────────────────────────────────────────────────────
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=pipeline
    env_file:
      - ./config/hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./config/hadoop.env
    depends_on:
      - namenode
 
  # ── SPARK ───────────────────────────────────────────────────────────────────
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8081:8080"
      - "7077:7077"
    command: >
      bash -c "/opt/spark/sbin/start-master.sh && tail -f /opt/spark/logs/*"
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
 
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    command: >
      bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /opt/spark/logs/*"
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4G
 
  # ── MONGODB ─────────────────────────────────────────────────────────────────
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
 
  # ── TOR (ROTATION IP) ───────────────────────────────────────────────────────
  tor1:
    image: dperson/torproxy
    container_name: tor1
    restart: unless-stopped
    ports:
      - "9050:9050"
    environment:
      - CONTROL_PASSWORD=mypass
    networks:
      - kbo

  tor2:
    image: dperson/torproxy
    container_name: tor2
    restart: unless-stopped
    ports:
      - "9052:9050"
    environment:
      - CONTROL_PASSWORD=mypass
    networks:
      - kbo
 

volumes:
  hadoop_namenode:
  hadoop_datanode:
  mongodb_data:


networks:
  kbo:
    external: true